framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true

        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
                    multiplier: 3
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'


        routing:
            'App\Message\ProcessSendNotificationRequest': async
