# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.mocked_user.email: '%env(MOCKED_USER_EMAIL)%'
    app.mocked_user.phone: '%env(MOCKED_USER_PHONE_NUMBER)%'
    app.channels_enabled: '%env(CHANNELS_ENABLED)%'
    app.channel_providers:
        email: '%env(CHANNEL_PROVIDERS_EMAIL)%'
        sms: '%env(CHANNEL_PROVIDERS_SMS)%'
        push: '%env(CHANNEL_PROVIDERS_PUSH)%'
    app.sms_send_from_number: '%env(SMS_SEND_FROM_NUMBER)%'
    app.email_send_from_name: '%env(EMAIL_SEND_FROM_NAME)%'
    app.email_send_from_address: '%env(EMAIL_SEND_FROM_ADDRESS)%'
    app.email_default_subj: '%env(EMAIL_DEFAULT_SUBJ)%'
    app.provider.twilio.account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    app.provider.twilio.auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    app.provider.twilio.phone_number: '%env(TWILIO_PHONE_NUMBER)%'
    app.provider.awsses.access_key: '%env(AWS_SES_ACCESS_KEY)%'
    app.provider.awsses.secret: '%env(AWS_SES_SECRET)%'
    app.provider.awsses.region: '%env(AWS_SES_REGION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Resolver\UserResolverInterface:
        class: App\Resolver\MockedUserResolver
        arguments:
            - '%app.mocked_user.email%'
            - '%app.mocked_user.phone%'

    App\Resolver\SupportedChannelsResolverInterface:
        class: App\Resolver\SupportedChannelsResolver
        arguments:
            - '%app.channels_enabled%'
            - '%app.channel_providers%'

    App\ServiceProvider\Strategy\SmsStrategy:
        arguments:
            - '%app.sms_send_from_number%'

    App\ServiceProvider\Strategy\EmailStrategy:
        arguments:
            - '%app.email_send_from_name%'
            - '%app.email_send_from_address%'
            - '%app.email_default_subj%'

    App\ServiceProvider\Adapter\TwilioSmsAdapter:
        arguments:
            - '%app.provider.twilio.account_sid%'
            - '%app.provider.twilio.auth_token%'
            - '%app.provider.twilio.phone_number%'

    App\ServiceProvider\Adapter\AwsSesEmailAdapter:
        arguments:
            - '%app.provider.awsses.access_key%'
            - '%app.provider.awsses.secret%'
            - '%app.provider.awsses.region%'